---
title: "COVID-Mex"
output: html_notebook
---

Introducción: 
En este proyecto se construirá un modelo logístico que determine las probabilidades de morir a causa del COVID-19 en México dependiendo de las condiciones de riesgo preexistentes de los pacientes al ser internados. 

Este proyecto es realizado utilizando las bases de datos históricas del COVID-19 proporcionadas por la Secretaría de Salud. Disponibles en https://www.gob.mx/salud/documentos/datos-abiertos-bases-historicas-direccion-general-de-epidemiologia 

```{r}
df <- read.csv('201031COVID19MEXICO.csv')
head(df)
print('hi')
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
